---

- hosts: all
  tasks:

#for Debian or Ubuntu
  - name: install appache2 package
    package:
      name: 
        - "{{ apache }}"
        - "{{ php }}"
      state: latest
      update_cache: yes


