---

- hosts: all
  tasks:


  - name: update repository index
    apt:
      update_cache: yes

  - name: install appache2 package
    apt:
      name: apache2
      state: absent

  - name: ass php support for appache
    apt:
      name: libapache2-mod-php
      state: absent
