---

- hosts: all
  become: true
  tasks:


  - name: update repository index
    apt:
      update_cache: yes

  - name: install appache2 package
    apt:
      name: apache2
      state: absent

  - name: install php support for appache
    apt:
      name: libapache2-mod-php
      state: absent

  - name: install samba
    apt:
      name: samba
      state: absent
